const NameSpace = {
  USER: `user`,
  /*CACHE_MEMORY: `cacheMemory`,
  ADMIN_USERS: `adminUsers`,
  ADMIN_MANAGER_TASKS: `adminManagerTasks`,
  ADMIN_COMPANIES: `ADMIN_COMPANIES`,
  ADMIN_INVOICES: `ADMIN_INVOICES`,
  ADMIN_HOUSES: `ADMIN_HOUSES`,
  ADMIN_FLATS: `ADMIN_FLATS`,
  ADMIN_MANAGERS: `ADMIN_MANAGERS`,
  ADMIN_CART: `ADMIN_CART`,*/
};

export default NameSpace;
